### ISSUE TITLE
The Content Area Was Not Found in Your Page

### ISSUE THREAD

**Issue by cherrybloom22** [wpexplorer/wpex-pytheas#1]
Hi,
I am using this template and I love it. However recently I realiised anytime I want to edit contents using elementor plugin (which i have used since adopting the template) it brings up this error:
"Sorry, the content area was not found in your page. You must call the_content function in the current template, in order for Elementor to work on this page."

I tried adding the following code (<?php the_content(); ?>) to all the template pages i saw within the theme but that didn't solve the problem. Please any ideas how i can solve the issue or are their any updates to the template resolving the issue with elementor? 

By the way please not i disabled all other plugins as well except elementor in my search for solution to no avail.

Thanks for the assistance to such a nice template.

**Comment by wpexplorer** [comment]
@cherrybloom22 

Hi,

Everything is working for me when testing Elementor - https://cl.ly/oPps (ignore the weird styling, I was testing the customizer settings recently).

Does the error happen on any page? Did you try a new page? The function mentioned in the erro definitely exists in the theme, so the plugin is showing a misleading error. Usually this happens due to redirections or permalink errors, can you check?

**Comment by cherrybloom22** [comment]
Hi, thanks for replying.
The problem is for all pages in the admin area. I just can’t modify any page using elementor. Please see attached screenshot to view the error.

Thanks


Sent from Mail for Windows 10

**Comment by wpexplorer** [comment]
@cherrybloom22 - The issue isn't with the theme though since it's working for me with all pages. You'll need to reach out to Elementor for assistance on this one.

Did you already try de-activating plugins incase a plugin is breaking things?

**Comment by cherrybloom22** [comment]
Hey thanks for responding. Apparently the problem may not have been from  Elementor or my host as opined by Elementor. I got in touch with my host initially who also referred me to elementor. Then Elementor indicated I send my system info to them and the further instructed I get in touch with my host to change some server settings.After all done I still could not edit until my host(siteground) suggested I use another browser and use Chrome ‎incognito mode and that worked. So now I am thinking it might be a browser or plugin issue with Chrome even though I disabled all plugins and flushed my cache.Thanks though for the feedback.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: WPExplorerSent: Thursday, December 28, 2017 22:05To: wpexplorer/wpex-pytheasReply To: wpexplorer/wpex-pytheasCc: cherrybloom22; MentionSubject: Re: [wpexplorer/wpex-pytheas] The Content Area Was Not Found in Your Page (#1)@cherrybloom22 - The issue isn't with the theme though since it's working for me with all pages. You'll need to reach out to Elementor for assistance on this one.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wpexplorer/wpex-pytheas","title":"wpexplorer/wpex-pytheas","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wpexplorer/wpex-pytheas"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wpexplorer in #1: @cherrybloom22 - The issue isn't with the theme though since it's working for me with all pages. You'll need to reach out to Elementor for assistance on this one."}],"action":{"name":"View Issue","url":"https://github.com/wpexplorer/wpex-pytheas/issues/1#issuecomment-354357758"}}}

**Comment by wpexplorer** [comment]
@cherrybloom22 - Awesome, I'm glad it's working now.I tested in Chrome and didn't have any issues (on my Mac) I would recommend double checking any addons (be very careful with chrome/firefox or any browser addons they could hack your WP site). And make sure everything is up to date!

ps: New free business themes coming 2018! With a whole new framework and support for WooCommerce, bbpress etc. Stay tuned ;)
